version: '2'

services:
  ewbf:
    container_name: ewbf
    build: .
  environment:
    SERVER: "${SERVER}"
    ADDRESS: "${ADDRESS}"
    WORKER: "${WORKER}"
    PASS: "${PASS}"
    PORT: "${PORT}"
  ports:
    - "42000:42000"
